export const navigation = [
    { title: 'Additional', url: '/additional', description: '' },
    { title: 'Accordion fold', url: '/aw-accordion-fold', description: '' },
    { title: 'Address', url: '/aw-address', description: '' },
    { title: 'Avatar', url: '/aw-avatar', description: '' },
    { title: 'Badge', url: '/aw-badge', description: '' },
    { title: 'Button nav', url: '/aw-button-nav', description: '' },
    { title: 'Button', url: '/aw-button', description: '' },
    { title: 'Calendar', url: '/aw-calendar', description: '' },
    { title: 'Card', url: '/aw-card', description: '' },
    { title: 'Chart', url: '/aw-chart', description: '' },
    { title: 'Checkbox', url: '/aw-checkbox', description: '' },
    { title: 'Chip', url: '/aw-chip', description: '' },
    {
        title: 'ChipSelect',
        url: '/aw-chip-select',
        description: 'Component for toggling statuses'
    },
    { title: 'Code', url: '/aw-code', description: '' },
    { title: 'Context menu', url: '/aw-context-menu', description: '' },
    { title: 'Cropper', url: '/aw-cropper', description: '' },
    { title: 'Date', url: '/aw-date', description: '' },
    { title: 'Dashboard Line', url: '/dashboard/line', description: '' },
    {
        title: 'Dashboard Donut',
        url: '/dashboard/donut',
        description: ''
    },
    {
        title: 'Dashboard Progress',
        url: '/dashboard/progress',
        description: ''
    },
    {
        title: 'Dashboard Section',
        url: '/dashboard/section',
        description: ''
    },
    {
        title: 'Dashboard Speed',
        url: '/dashboard/speed',
        description: ''
    },
    { title: 'Dropdowns', url: '/aw-dropdown', description: '' },
    { title: 'Fetch data', url: '/aw-fetch-data', description: '' },
    { title: 'Form', url: '/aw-form', description: '' },
    { title: 'Grid', url: '/aw-grid', description: '' },
    { title: 'Icon', url: '/aw-icon', description: '' },
    { title: 'Info', url: '/aw-info', description: '' },
    { title: 'Input', url: '/aw-input', description: '' },
    { title: 'Link', url: '/aw-link', description: '' },
    { title: 'Markdown editor', url: '/aw-markdown-editor', description: '' },
    { title: 'Modal', url: '/aw-modal', description: '' },
    { title: 'Notify', url: '/notify', description: '' },
    { title: 'Radio', url: '/aw-radio', description: '' },
    { title: 'Search', url: '/aw-search', description: '' },
    { title: 'Select', url: '/aw-select', description: '' },
    { title: 'Select multiple', url: '/aw-select_multiple', description: '' },
    { title: 'Select ajax', url: '/aw-select_ajax', description: '' },
    { title: 'Select object', url: '/aw-select_object', description: '' },
    { title: 'Switcher', url: '/aw-switcher', description: '' },
    { title: 'Tab nav', url: '/aw-tab-nav', description: '' },
    { title: 'Table', url: '/table/', description: '' },
    { title: 'Table orderable', url: '/table/orderable', description: '' },
    { title: 'Table pagination', url: '/table/pagination', description: '' },
    { title: 'Timeline builder', url: '/aw-timeline-builder', description: '' },
    { title: 'Toggler', url: '/aw-toggler', description: '' },
    { title: 'Tooltip', url: '/v-tooltip', description: '' },
    { title: 'Uploader', url: '/aw-uploader', description: '' }
]
