export const navigation = [
    { title: 'Accordion fold', url: '/aw-accordion-fold', description: '' },
    { title: 'Address', url: '/aw-address', description: '' },
    { title: 'Avatar', url: '/aw-avatar', description: '' },
    { title: 'Button nav', url: '/aw-button-nav', description: '' },
    { title: 'Button', url: '/aw-button', description: '' },
    { title: 'Calendar', url: '/aw-calendar', description: '' },
    { title: 'Card', url: '/aw-card', description: '' },
    { title: 'Chart', url: '/aw-chart', description: '' },
    { title: 'Checkbox', url: '/aw-checkbox', description: '' },
    { title: 'Chip', url: '/aw-chip', description: '' },
    { title: 'Code', url: '/aw-code', description: '' },
    { title: 'Cropper', url: '/aw-cropper', description: '' },
    { title: 'Date', url: '/aw-date', description: '' },
    { title: 'Dropdowns', url: '/aw-dropdowns', description: '' },
    { title: 'Form', url: '/aw-form', description: '' },
    { title: 'Grid', url: '/aw-grid', description: '' },
    { title: 'Icon', url: '/aw-icon', description: '' },
    { title: 'Info', url: '/aw-info', description: '' },
    { title: 'Input', url: '/aw-input', description: '' },
    { title: 'Link', url: '/aw-link', description: '' },
    { title: 'Markdown editor', url: '/aw-markdown-editor', description: '' },
    { title: 'Modal', url: '/aw-modal', description: '' },
    { title: 'Radio', url: '/aw-radio', description: '' },
    { title: 'Search', url: '/aw-search', description: '' },
    { title: 'Select', url: '/aw-select', description: '' },
    { title: 'Select ajax', url: '/aw-select_ajax', description: '' },
    { title: 'Select object', url: '/aw-select_object', description: '' },
    { title: 'Switcher', url: '/aw-switcher', description: '' },
    { title: 'Tab nav', url: '/aw-tab-nav', description: '' },
    { title: 'Table', url: '/aw-table', description: '' },
    { title: 'Timeline builder', url: '/aw-timeline-builder', description: '' },
    { title: 'Uploader', url: '/aw-uploader', description: '' }
]
